package jmeter

import (
	"fmt"
	"strings"
)

// TestPlanConfig holds configuration for generating a JMeter test plan
type TestPlanConfig struct {
	TargetURL    string
	VirtualUsers int
	Duration     int
	RampUp       int
	Protocol     string
	HTTPMethod   string
	Headers      map[string]string
	Body         string
	ThinkTime    int // milliseconds
}

// GenerateTestPlan creates a JMeter test plan XML from configuration
func GenerateTestPlan(config TestPlanConfig) string {
	if config.Protocol == "" {
		config.Protocol = "http"
	}
	if config.HTTPMethod == "" {
		config.HTTPMethod = "GET"
	}
	if config.ThinkTime == 0 {
		config.ThinkTime = 1000
	}

	// Build headers XML
	headersXML := ""
	if len(config.Headers) > 0 {
		headersXML = "\n            <hashTree>"
		for key, value := range config.Headers {
			headersXML += fmt.Sprintf(`
              <HeaderManager guiclass="HeaderPanel" testclass="HeaderManager" testname="HTTP Header Manager" enabled="true">
                <collectionProp name="HeaderManager.headers">
                  <elementProp name="" elementType="Header">
                    <stringProp name="Header.name">%s</stringProp>
                    <stringProp name="Header.value">%s</stringProp>
                  </elementProp>
                </collectionProp>
              </HeaderManager>
              <hashTree/>`, key, value)
		}
		headersXML += "\n            </hashTree>"
	}

	// Build body XML
	bodyXML := ""
	if config.Body != "" {
		bodyXML = fmt.Sprintf(`
              <boolProp name="HTTPSampler.postBodyRaw">true</boolProp>
              <elementProp name="HTTPsampler.Arguments" elementType="Arguments">
                <collectionProp name="Arguments.arguments">
                  <elementProp name="" elementType="HTTPArgument">
                    <boolProp name="HTTPArgument.always_encode">false</boolProp>
                    <stringProp name="Argument.value">%s</stringProp>
                    <stringProp name="Argument.metadata">=</stringProp>
                  </elementProp>
                </collectionProp>
              </elementProp>`, config.Body)
	}

	return fmt.Sprintf(`<?xml version="1.0" encoding="UTF-8"?>
<jmeterTestPlan version="1.2" properties="5.0" jmeter="5.6.3">
  <hashTree>
    <TestPlan guiclass="TestPlanGui" testclass="TestPlan" testname="MarathonRunner Test Plan" enabled="true">
      <boolProp name="TestPlan.functional_mode">false</boolProp>
      <boolProp name="TestPlan.serialize_threadgroups">false</boolProp>
      <stringProp name="TestPlan.comments">Generated by MarathonRunner Enterprise</stringProp>
      <elementProp name="TestPlan.user_defined_variables" elementType="Arguments">
        <collectionProp name="Arguments.arguments"/>
      </elementProp>
    </TestPlan>
    <hashTree>
      <ThreadGroup guiclass="ThreadGroupGui" testclass="ThreadGroup" testname="Load Test Group" enabled="true">
        <intProp name="ThreadGroup.num_threads">%d</intProp>
        <intProp name="ThreadGroup.ramp_time">%d</intProp>
        <boolProp name="ThreadGroup.scheduler">true</boolProp>
        <stringProp name="ThreadGroup.duration">%d</stringProp>
        <stringProp name="ThreadGroup.delay">0</stringProp>
        <stringProp name="ThreadGroup.on_sample_error">continue</stringProp>
      </ThreadGroup>
      <hashTree>
        <HTTPSamplerProxy guiclass="HttpTestSampleGui" testclass="HTTPSamplerProxy" testname="HTTP Request" enabled="true">
          <stringProp name="HTTPSampler.domain">${__P(target_host,%s)}</stringProp>
          <stringProp name="HTTPSampler.port">${__P(target_port,80)}</stringProp>
          <stringProp name="HTTPSampler.protocol">%s</stringProp>
          <stringProp name="HTTPSampler.path">/</stringProp>
          <stringProp name="HTTPSampler.method">%s</stringProp>
          <boolProp name="HTTPSampler.follow_redirects">true</boolProp>
          <boolProp name="HTTPSampler.auto_redirects">false</boolProp>
          <boolProp name="HTTPSampler.use_keepalive">true</boolProp>
          <boolProp name="HTTPSampler.DO_MULTIPART_POST">false</boolProp>
          <stringProp name="HTTPSampler.embedded_url_re"></stringProp>
          <stringProp name="HTTPSampler.connect_timeout">5000</stringProp>
          <stringProp name="HTTPSampler.response_timeout">30000</stringProp>%s
        </HTTPSamplerProxy>%s
        <ConstantTimer guiclass="ConstantTimerGui" testclass="ConstantTimer" testname="Think Time" enabled="true">
          <stringProp name="ConstantTimer.delay">%d</stringProp>
        </ConstantTimer>
        <hashTree/>
        <ResponseAssertion guiclass="AssertionGui" testclass="ResponseAssertion" testname="Response Assertion" enabled="true">
          <collectionProp name="Asserion.test_strings">
            <stringProp name="49586">200</stringProp>
          </collectionProp>
          <stringProp name="Assertion.test_field">Assertion.response_code</stringProp>
          <intProp name="Assertion.test_type">1</intProp>
          <stringProp name="Assertion.scope">all</stringProp>
        </ResponseAssertion>
        <hashTree/>
      </hashTree>
    </hashTree>
  </hashTree>
</jmeterTestPlan>`, config.VirtualUsers, config.RampUp, config.Duration,
		config.TargetURL, config.Protocol, config.HTTPMethod,
		bodyXML, headersXML, config.ThinkTime)
}

// GenerateDistributedTestPlan creates a test plan for distributed execution
func GenerateDistributedTestPlan(config TestPlanConfig, workerCount int) string {
	// For distributed execution, we split virtual users across workers
	workersPerNode := config.VirtualUsers / workerCount
	if workersPerNode < 1 {
		workersPerNode = 1
	}

	return GenerateTestPlan(TestPlanConfig{
		TargetURL:    config.TargetURL,
		VirtualUsers: workersPerNode,
		Duration:     config.Duration,
		RampUp:       config.RampUp,
		Protocol:     config.Protocol,
		HTTPMethod:   config.HTTPMethod,
		Headers:      config.Headers,
		Body:         config.Body,
		ThinkTime:    config.ThinkTime,
	})
}

// ParseConnectionString parses a URL into protocol, host, and port
func ParseConnectionString(url string) (protocol, host, port string) {
	protocol = "http"
	host = url
	port = "80"

	if strings.HasPrefix(url, "https://") {
		protocol = "https"
		host = strings.TrimPrefix(url, "https://")
		port = "443"
	} else if strings.HasPrefix(url, "http://") {
		host = strings.TrimPrefix(url, "http://")
	}

	// Remove path if present
	if idx := strings.Index(host, "/"); idx != -1 {
		host = host[:idx]
	}

	// Check for port
	if idx := strings.Index(host, ":"); idx != -1 {
		port = host[idx+1:]
		host = host[:idx]
	}

	return protocol, host, port
}
