{{- if .Values.nginx.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "speedrunner.fullname" . }}-nginx
  labels:
    {{- include "speedrunner.labels" . | nindent 4 }}
    app.kubernetes.io/component: nginx
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "speedrunner.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: nginx
{{- end }}
