{{- if .Values.postgresStandalone.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "speedrunner.fullname" . }}-postgres
  labels:
    {{- include "speedrunner.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.postgres.port }}
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    {{- include "speedrunner.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
{{- end }}
