{{- if and .Values.redisStandalone.enabled .Values.redisStandalone.storage.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "speedrunner.fullname" . }}-redis
  labels:
    {{- include "speedrunner.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.redisStandalone.storage.storageClass }}
  storageClassName: {{ .Values.redisStandalone.storage.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.redisStandalone.storage.size }}
{{- end }}
