apiVersion: v1
kind: Secret
metadata:
  name: {{ include "speedrunner.fullname" . }}-secret
  labels:
    {{- include "speedrunner.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.postgres.password }}
  postgres-password: {{ .Values.postgres.password | b64enc | quote }}
  {{- end }}
  {{- if .Values.redis.password }}
  redis-password: {{ .Values.redis.password | b64enc | quote }}
  {{- end }}
