apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: performancetests.speedrunner.io
spec:
  group: speedrunner.io
  names:
    kind: PerformanceTest
    listKind: PerformanceTestList
    plural: performancetests
    singular: performancetest
    shortNames: [ptest]
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required: [targetUrl, virtualUsers]
              properties:
                name:
                  type: string
                targetUrl:
                  type: string
                virtualUsers:
                  type: integer
                  minimum: 1
                durationSec:
                  type: integer
                  default: 300
                engine:
                  type: string
                  enum: [simulate, http, jmeter, k6, gatling, locust, playwright]
                  default: jmeter
                region:
                  type: string
                schedule:
                  type: string
                  description: Optional cron expression
            status:
              type: object
              properties:
                phase:
                  type: string
                lastRunId:
                  type: string
                message:
                  type: string
      subresources:
        status: {}
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: testruns.speedrunner.io
spec:
  group: speedrunner.io
  names:
    kind: TestRun
    listKind: TestRunList
    plural: testruns
    singular: testrun
    shortNames: [trun]
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required: [testRef]
              properties:
                testRef:
                  type: string
                  description: Name of PerformanceTest CR or platform test ID
                engine:
                  type: string
                virtualUsers:
                  type: integer
                durationSec:
                  type: integer
            status:
              type: object
              properties:
                phase:
                  type: string
                  enum: [Pending, Running, Succeeded, Failed, Cancelled]
                jobName:
                  type: string
                startedAt:
                  type: string
                completedAt:
                  type: string
                message:
                  type: string
      subresources:
        status: {}
